INSERT INTO roles(nombre, descripcion) VALUES('APRENDIZ', 'Rol de APRENDIZ');

INSERT INTO usuarios (nombre, apellido, correo, clave, fecha_registro, rol_id) VALUES ('Jarlin','Fonseca', 'jarlinfonseca@gmail.com', '$2a$12$jrk350scTSD6wlmAtLfF1OeRPkVXCGtL7/33BkJwzXPaTJWYbVQeW', current_timestamp, 1);

INSERT INTO rutas (nombre, descripcion) VALUES('Ruta de Backend', 'Esta es la ruta donde aprenderás mucho sobre Backend.');
INSERT INTO rutas (nombre, descripcion) VALUES('Ruta de Frontend', 'Esta es la ruta donde aprenderás mucho sobre Frontend.');
INSERT INTO rutas (nombre, descripcion) VALUES('Ruta de DataBase', 'Esta es la ruta donde aprenderás mucho sobre DataBase.');
INSERT INTO rutas (nombre, descripcion) VALUES('Ruta de DevOps', 'Esta es la ruta donde aprenderás mucho sobre DevOps.');


INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('Java','Esta etapa es la intro al mundo de Java.', 1);
INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('PHP','Esta es la segunda etapa de esta ruta.', 1);

INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('HTML','Esta etapa es la intro al mundo de Frontend.', 2);
INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('CSS','Esta es la segunda etapa de esta ruta.', 2);
INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('JavaScript','Esta es la tercera etapa de esta ruta.', 2);

INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('MySQL','Esta etapa es la intro al mundo de DataBase', 3);

INSERT INTO etapas (nombre, descripcion, ruta_id) VALUES('DevOps','Esta etapa es la intro al mundo de DevOps', 4);


INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'Java es un lenguaje de programación versátil y ampliamente utilizado que ofrece una plataforma sólida para el desarrollo de aplicaciones. Diseñado para ser fácil de entender y escribir, Java es especialmente conocido por su portabilidad y capacidad de ejecutarse en diversos entornos.', 1);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En un nivel intermedio, Java revela su potencial completo ofreciendo a los desarrolladores herramientas avanzadas y conceptos más profundos. La programación orientada a objetos se enriquece con la implementación de patrones de diseño, reflexión y anotaciones personalizadas. La concurrencia y la programación funcional con expresiones lambda y Streams API brindan soluciones eficientes para manipular datos y procesos en entornos multihilo. Además, el desarrollo web con Spring, la persistencia de datos mediante JPA y Hibernate, así como la programación reactiva, expanden el horizonte de posibilidades, permitiendo a los desarrolladores abordar proyectos más complejos con confianza y eficacia.', 1);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'En el nivel avanzado, Java se convierte en una herramienta poderosa para enfrentar los desafíos más complejos del desarrollo de software. Los desarrolladores experimentados aprovechan al máximo la programación orientada a objetos, empleando patrones de diseño avanzados y técnicas de optimización de rendimiento. La concurrencia se gestiona con precisión utilizando Locks y Programación Reactiva, mientras que la programación funcional, respaldada por expresiones lambda y Streams API, permite construir sistemas altamente eficientes. La integración con frameworks empresariales como Spring y el uso experto de persistencia de datos mediante JPA y Hibernate demuestran la capacidad de Java para impulsar aplicaciones a escala empresarial, garantizando la robustez y la escalabilidad en proyectos de envergadura.', 1);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'Java', 1);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'PHP, un lenguaje de programación del lado del servidor, es ideal para quienes dan sus primeros pasos en el desarrollo web dinámico. Con una sintaxis sencilla y flexible, PHP permite la incorporación de código directamente en HTML, facilitando la creación de páginas web interactivas. Los conceptos básicos incluyen variables, estructuras de control y funciones, brindando a los principiantes las herramientas necesarias para construir sitios web dinámicos e interactivos de manera accesible. Su integración natural con bases de datos, como MySQL, también lo convierte en una elección popular para aplicaciones web.', 2);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En un nivel intermedio de PHP, los desarrolladores expanden su expertise para construir aplicaciones web más robustas y eficientes. Profundizando en conceptos como la manipulación avanzada de arrays, programación orientada a objetos y el uso de frameworks populares como Laravel, se potencia la capacidad para desarrollar sistemas escalables y mantenibles. Además, la integración de PHP con tecnologías como AJAX y la implementación de seguridad avanzada, como la prevención de inyecciones SQL, contribuyen a un desarrollo web más sofisticado y seguro.', 2);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'En el nivel avanzado de PHP, los desarrolladores alcanzan un dominio experto, aprovechando técnicas avanzadas de programación orientada a objetos y patrones de diseño. La optimización del rendimiento a través de técnicas de caché y la implementación de arquitecturas de software como microservicios o API RESTful se convierten en enfoques comunes. Además, la seguridad se refuerza mediante prácticas avanzadas, como el uso de cifrado y la autenticación multifactor, consolidando PHP como una herramienta clave para el desarrollo de aplicaciones web altamente complejas y seguras.', 2);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'PHP', 2);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'HTML (Lenguaje de Marcado de Hipertexto) en su nivel básico sirve como el cimiento esencial para la creación de páginas web. Este lenguaje sencillo y estructurado permite a quienes están iniciando en el desarrollo web definir la estructura básica de una página. Los elementos básicos, como encabezados, párrafos, listas y enlaces, se utilizan para organizar y presentar información de manera clara. Además, los conceptos introductorios de atributos y etiquetas proporcionan a los principiantes las herramientas fundamentales para comenzar a construir contenidos web estáticos.', 3);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En el nivel intermedio de HTML, los desarrolladores profundizan en la creación de páginas web, incorporando conceptos más avanzados para lograr diseños y funcionalidades más complejas. Se exploran etiquetas semánticas como <article>, <section>, y <nav>, permitiendo una estructuración más precisa del contenido. Además, el uso avanzado de formularios con elementos como <input> y <select>, junto con la manipulación de estilos mediante CSS, ofrece a los desarrolladores intermedios la capacidad de crear experiencias de usuario más interactivas y atractivas. La comprensión de conceptos como accesibilidad web y SEO se vuelve más profunda, contribuyendo a la creación de sitios web más inclusivos y optimizados para motores de búsqueda.', 3);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'En el nivel avanzado de HTML, los desarrolladores alcanzan un dominio experto en la creación de experiencias web sofisticadas y altamente funcionales. La implementación de tecnologías modernas como HTML5 y el uso de elementos como <canvas> y <video> permite la creación de contenido multimedia y gráficos dinámicos. La incorporación de APIs, como la API de geolocalización o la API de notificaciones, amplía las capacidades interactivas de las aplicaciones web. Además, la optimización del rendimiento a través de técnicas avanzadas, como la carga asíncrona de recursos y la gestión eficiente de la memoria, asegura experiencias de usuario rápidas y fluidas. La atención meticulosa a la accesibilidad y la implementación de estándares web garantizan que los sitios sean no solo visualmente atractivos, sino también inclusivos y compatibles con diversos dispositivos y navegadores.', 3);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'HTML', 3);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'En el nivel básico de CSS (Cascading Style Sheets), los principiantes se introducen en el arte de dar estilo a páginas web. CSS se utiliza para controlar el diseño y la presentación de los elementos HTML, permitiendo la modificación de colores, fuentes, márgenes y alineaciones. Los conceptos iniciales incluyen la aplicación de estilos a través de selecciones de elementos, clases y ID, proporcionando a los principiantes una comprensión fundamental de cómo dar forma y diseño a sus páginas web de manera visualmente atractiva.', 4);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En el nivel intermedio de CSS, los desarrolladores profundizan en la creación de estilos más complejos y dinámicos para mejorar la apariencia y la interactividad de las páginas web. Se exploran conceptos avanzados como el posicionamiento CSS, flexbox y grid, permitiendo un diseño más fluido y adaptable. Además, se introducen transiciones y animaciones CSS para agregar dinamismo a los elementos de la interfaz. La comprensión de selectores avanzados y la organización eficiente del código CSS mediante preprocesadores como Sass mejoran la mantenibilidad del estilo. En este nivel, los desarrolladores también pueden abordar problemas de compatibilidad entre navegadores y adoptar prácticas de diseño responsivo para optimizar la visualización en diversos dispositivos.', 4);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'En el nivel avanzado de CSS, los desarrolladores alcanzan una maestría en la creación de interfaces web altamente sofisticadas y atractivas. Se exploran técnicas avanzadas de diseño responsivo, utilizando media queries y viewport units para adaptar la presentación a una variedad de dispositivos y tamaños de pantalla. La implementación de animaciones y transformaciones CSS3 proporciona interactividad y dinamismo sin necesidad de JavaScript. El uso experto de sistemas de diseño como BEM (Block Element Modifier) y arquitecturas CSS como ITCSS (Inverted Triangle CSS) optimizan la organización y escalabilidad del código. Además, la familiaridad con metodologías como SMACSS (Scalable and Modular Architecture for CSS) y la consideración de la accesibilidad en el diseño reflejan la sofisticación y la calidad en el desarrollo de estilos avanzados con CSS.', 4);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'CSS', 4);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'En el nivel básico de JavaScript, los principiantes se adentran en el emocionante mundo de la programación del lado del cliente. JavaScript, el lenguaje de scripting esencial para el desarrollo web, permite a los desarrolladores dar vida a sus páginas web. En este nivel, los conceptos fundamentales como variables, tipos de datos, estructuras de control de flujo (como bucles y condicionales) y funciones sientan las bases para manipular el contenido y responder a la interacción del usuario. Los principiantes comienzan a comprender cómo JavaScript se integra con el HTML y el CSS, desbloqueando el potencial para crear experiencias web más dinámicas y atractivas.', 5);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En el nivel intermedio de JavaScript, los desarrolladores avanzan más allá de los conceptos básicos para abordar problemas más complejos en el desarrollo web. Se explora en profundidad la programación orientada a objetos, permitiendo la creación de código modular y reutilizable. El manejo avanzado de eventos y manipulación del DOM (Documento Object Model) permite una interactividad más dinámica, mientras que las solicitudes asíncronas con XMLHttpRequest o Fetch facilitan la comunicación con servidores. Además, el estudio de conceptos como closures, callbacks y promesas contribuye a la creación de código más eficiente y fácil de mantener. Los desarrolladores intermedios de JavaScript también pueden empezar a explorar bibliotecas populares como jQuery o frameworks como React y Vue.js para potenciar aún más sus habilidades en el desarrollo web.', 5);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'En el nivel avanzado de JavaScript, los desarrolladores perfeccionan la manipulación del DOM, adoptan patrones de diseño como el patrón módulo, y aplican prácticas avanzadas de programación asincrónica con Promises y Generators. La experiencia en frameworks modernos, como React y Vue.js, así como la implementación eficaz de herramientas de construcción y bundling, reflejan una capacidad excepcional para crear aplicaciones web altamente eficientes y escalables.', 5);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'Js', 5);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'MySQL es un sistema de gestión de bases de datos relacional de código abierto. Su interfaz sencilla y fácil de usar lo hace ideal para usuarios principiantes. Permite almacenar, organizar y recuperar datos eficientemente a través de consultas simples. Con soporte para múltiples plataformas, MySQL es una opción popular para aplicaciones web y proyectos de desarrollo de software.', 6);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'En un nivel intermedio, MySQL se revela como una herramienta potente con capacidades avanzadas. Su lenguaje de consulta SQL permite realizar operaciones complejas, como joins y subconsultas, optimizando la manipulación de datos. La gestión de índices y transacciones garantiza la integridad y consistencia de la base de datos, crucial para aplicaciones más robustas. Además, la capacidad de configuración avanzada y la optimización del rendimiento ofrecen a los usuarios intermedios un mayor control sobre la eficiencia y escalabilidad de sus sistemas basados en MySQL.', 6);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'A nivel avanzado, MySQL se destaca por su capacidad para manejar entornos de datos a gran escala y complejidad. Los expertos pueden implementar técnicas avanzadas de optimización, como particionamiento de tablas y ajustes finos de configuración, para optimizar el rendimiento en situaciones exigentes. La replicación avanzada y las características de alta disponibilidad garantizan la fiabilidad y la recuperación ante fallos en entornos críticos. MySQL también ofrece soporte para procedimientos almacenados, disparadores y funciones definidas por el usuario, permitiendo una lógica de negocio más compleja directamente en la base de datos. En resumen, a nivel avanzado, MySQL se convierte en una herramienta robusta y escalable, capaz de abordar desafíos significativos en la gestión de datos a gran escala.', 6);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'MySQL', 6);

INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 1 - Conocimientos básicos', 'DevOps, a nivel básico, fusiona desarrollo y operaciones para mejorar la colaboración en el ciclo de vida del software. Utiliza herramientas de automatización como Jenkins para agilizar la construcción y despliegue de aplicaciones. La infraestructura como código facilita la gestión automatizada de entornos. La comunicación constante y la monitorización contribuyen a la mejora continua del rendimiento del sistema.', 7);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 2 - Conocimientos intermedios', 'A nivel intermedio, DevOps implica la implementación avanzada de CI/CD para una entrega rápida y segura de software. La orquestación de contenedores, como Kubernetes, gestiona entornos complejos y dinámicos. La automatización se extiende a la monitorización, permitiendo una respuesta proactiva a problemas. La cultura DevOps se fortalece, promoviendo la colaboración estrecha y la responsabilidad compartida entre los equipos.', 7);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Nivel 3 - Conocimientos avanzados', 'A nivel avanzado, DevOps implica la implementación completa de estrategias CI/CD para despliegues seguros y frecuentes. La orquestación avanzada de contenedores, como con Kubernetes, gestiona entornos complejos con eficiencia. La automatización abarca desde la infraestructura hasta la monitorización, permitiendo respuestas rápidas a problemas. La cultura DevOps se arraiga profundamente, fomentando una colaboración estrecha y una mejora continua en todo el ciclo de vida del software.', 7);
INSERT INTO contenidos (titulo, descripcion, etapa_id) VALUES('Conocimientos Adicionales', 'DevOps', 7);

-- intro al mundo back
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Backend', 'Que aprender para ser programador en 2023?', 'https://youtu.be/0Zb5fgO0ubE', current_timestamp,1);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Backend1', 'De 0 a Programador Backend - Guia completa paso a paso', 'https://www.youtube.com/watch?v=RYvFfsUyOtk', current_timestamp,1);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Backend2', '¡Las 4 tecnologías para conseguir empleo como Back-End en 2023!', 'https://www.youtube.com/watch?v=UAt-Ae1YVaA&list=PLkVpKYNT_U9cW6CIloOeWFNn3Wjq2SPTZ', current_timestamp,1);
--intro al mundo front
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Frontend', '7 cosas que debes saber para ser programador frontend este 2023', 'https://youtu.be/q0UgClC8md4', current_timestamp,3);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Frontend1', 'FRONT-END EN 5 PASOS - ¿Que aprender y por donde empezar para ser Desarrollador Web Frontend?', 'https://www.youtube.com/watch?v=SDMpGO1_qU0', current_timestamp,3);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Video de Frontend2', '¡Conviértete en Front-End developer y encuentra trabajo con estas 3 tecnologías! ', 'https://www.youtube.com/watch?v=9qzTMGZOd20&list=PLkVpKYNT_U9cxPPzmABgbtO8MdJQ4P-sY', current_timestamp,3);

--Java
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Java', 'Programación JAVA Nivel Básico', 'https://www.youtube.com/playlist?list=PLyvsggKtwbLX9LrDnl1-K6QtYo7m0yXWB', current_timestamp,1);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Java', 'Programación JAVA Nivel Intermedio', 'https://www.youtube.com/playlist?list=PLyvsggKtwbLXEZjb8HrNTbWesTKIfpNak', current_timestamp,2);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('Java', 'Programación JAVA Nivel Avanzado', 'https://www.youtube.com/playlist?list=PLkVpKYNT_U9cbo0XywpRGl-DFJEHDi9g5', current_timestamp,3);

--PHP
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('PHP', 'Programación en PHP Nivel Básico', 'https://www.youtube.com/playlist?list=PL3b9xmg86NTKzt_Hkr0jywY-P5HY0gnjf', current_timestamp,4);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('PHP', 'Programación en PHP Nivel Intermedio', 'https://www.youtube.com/playlist?list=PL3HzJCml0goHUfWo61vsNnRCoEVHv1ggg', current_timestamp,5);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('PHP', 'Programación en PHP Nivel Avanzado', 'https://www.youtube.com/playlist?list=PLX64KYDfSBMsmf9MtXBNmTc845YVPBdU0', current_timestamp,6);


--HTML
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('HTML', 'Programación en HTML Nivel Básico', 'https://www.youtube.com/watch?v=rbuYtrNUxg4', current_timestamp,7);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('HTML', 'Programación en HTML Nivel Intermedio', 'https://www.youtube.com/playlist?list=PL80XT4wvmjbp4dZje4cyH9yUmtiItv_cm', current_timestamp,8);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('HTML', 'Programación en HTML Nivel Avanzado', 'https://www.youtube.com/playlist?list=PLg9145ptuAijj9GoHPTcYT8IoQAOchM-n', current_timestamp,9);

--CSS
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('CSS', 'Programación en CSS Nivel Básico', 'https://www.youtube.com/playlist?list=PLhSj3UTs2_yU0fGoS1bjpHqky4kCEmTbR', current_timestamp,10);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('CSS', 'Programación en CSS Nivel Intermedio', 'https://www.youtube.com/playlist?list=PLUmVO7Txjho0Sk7f1ccRcw4uvDdgzxMAb', current_timestamp,11);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('CSS', 'Programación en CSS Nivel Avanzado', 'https://www.youtube.com/playlist?list=PLg9145ptuAihoxLk6_fPLz0zD4o1S92ev', current_timestamp,12);


--JAVASCRIPT
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('JavaScript', 'Programación en JavaScript Nivel Básico', 'https://www.youtube.com/playlist?list=PLhSj3UTs2_yVC0iaCGf16glrrfXuiSd0G', current_timestamp,13);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('JavaScript', 'Programación en JavaScript Nivel Intermedio', 'https://www.youtube.com/playlist?list=PLAAhC8kCE0VlfmKREk2JJ-hFRPpTl3Daq', current_timestamp,14);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('JavaScript', 'Programación en JavaScript Nivel Avanzado', 'https://www.youtube.com/playlist?list=PLyBd7TyyK5mqBGx31fC5tvqOi6UbY2rMU', current_timestamp,15);

-- MySQL
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('MySQL', 'Programación en MySQL Nivel Básico', 'https://www.youtube.com/watch?v=_8MjEhfKRbI', current_timestamp,16);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('MySQL', 'Programación en MySQL Nivel Intermedio', 'https://www.youtube.com/playlist?list=PLYs5ugazzUNYxb-lqQexn-G5y5Pi_jbUb', current_timestamp,17);
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('MySQL', 'Programación en MySQL Nivel Avanzado', 'https://www.youtube.com/watch?v=X4ffVGDI2Fo', current_timestamp,18);

-- DevOps
INSERT INTO enlaces (nombre, descripcion, url_enlace, fecha_registro, contenido_id) VALUES('DevOps', 'Programación en DevOps', 'https://www.youtube.com/playlist?list=PL9prAn3zOWZ6HTdT_S4j2NXGhDyhTRoTh', current_timestamp,19);
